#' diffcp function
#'
#' Computes differential copy number genes between high and low group by Chi-squared test
#'
#' @param pat2 data frame generated by patsubset function
#' @param cp data frame of copy number matrix
#'
#' @import data.table
#'
#' @return data frame with frequency of copy number changes in high and low group with p-value from Chi-squared test
#'
#' @examples
#' gene <- "SOX10"
#' sox10.pat <- patsubset(pat, rna, gene, 10)
#' diffcp(sox10.pat, cp)
#'
#' @export
#'

diffcp <- function(pat2, cp) {
  setkey(pat2, gene2)
  #gets patients with rnaseq, clinical and mutation data
  overlap.high <- intersect(pat2["high", name], colnames(cp))
  overlap.low <- intersect(pat2["low", name], colnames(cp))

  cpmelt <- melt(cp, id.vars = "Gene", variable.name = "name")
  setkey(cpmelt, name)

  sum.high <- xtabs( ~ value + Gene,data = cpmelt[overlap.high])
  sum.low <- xtabs( ~ value + Gene, data = cpmelt[overlap.low])

  cpsum <- rbind(sum.high, sum.low)
  #creates matrix with 4 rows
  cp2 <- data.table(Gene = cp$Gene)

  cp2[, p.value := apply(cpsum, 2, function(x) {
    (chisq.test(matrix(x, 2, byrow = TRUE))$p.value)
  })]

  cp2[, FDR := p.adjust(p.value, method="BH")]
  setkey(cp2, p.value)
  cp2
}
