#' diffcp function
#'
#' Computes differential copy number genes between high and low group by Chi-squared test
#'
#' @param pat2 data frame generated by patsubset function
#' @param cp data frame of copy number matrix
#'
#' @import data.table
#'
#' @return data frame with frequency of copy number changes in high and low group with p-value from Chi-squared test
#'
#' @examples
#' gene <- "SOX10"
#' sox10.pat <- patsubset(pat, rna, gene, 10)
#' diffcp(sox10.pat, cp)
#'
#' @export
#'

diffcp <- function(pat2, cp) {
  setkey(pat2, gene2)
  #gets patients with rnaseq, clinical and mutation data
  overlap.high <- intersect(pat2["high", name], colnames(cp))
  overlap.low <- intersect(pat2["low", name], colnames(cp))

  #calculates most mutated genes in the overlap patients
  cp1 <- data.table(Gene = cp$Gene,
                   N.high = rowSums(abs(cp[, overlap.high, with =FALSE])),
                   N.hightotal = length(overlap.high),
                   N.low = rowSums(abs(cp[, overlap.low, with =FALSE])),
                   N.lowtotal = length(overlap.low))

  cp2 <- cp1[N.high + N.low != 0 & N.high + N.low != 1]
  #creates matrix with 4 rows
  xx = with(cp2, matrix(c(N.hightotal - N.high, N.high, N.lowtotal - N.low, N.low), 4, byrow=TRUE))

  cp2[, p.value := apply(xx, 2, function(x) {
    (chisq.test(matrix(x, 2))$p.value)
  })]

  cp2[, FDR := p.adjust(p.value, method="BH")]
  setkey(cp2, p.value)
  cp2
}
