#' genesurv function
#'
#' Draws survminer survival plot for high and low gene populations
#'
#' @param pat2 data frame generated by patsubset function
#' @param gene character(1) gene of interest
#'
#' @import data.table
#' @import survival
#' @import survminer
#'
#' @return survminer styled Survival plot
#'
#' @examples
#' gene <- "SOX10"
#' sox10 <- patsubset(pat, rna, gene, 10)
#' genesurv(sox10, gene)
#'
#' @export
#'
genesurv <- function(pat2, gene) {
  pat2.surv <- with(pat2, Surv(TCGA_year, vitalstatus) ~ gene2)
  survplot <- do.call(survfit, args=list(formula = pat2.surv, subset=(pat2$gene2 != "middle")))
  half <- summary(survplot)$table[,"median"]
  n <- summary(survplot)$table[,"records"]
  res <- ggsurvplot(survplot,
                    pval=T,
                    pval.coord = c(1,0.1),
                    conf.int = T,
                    risk.table = T,
                    risk.table.y.text = F,
                    break.time.by = 1,
                    palette = c("#1a1a1a", "#d7191c"),
                    legend = c(0.8, 0.8),
                    legend.title = "Gene level",
                    legend.labs = c(sprintf("%s high, n=%s\n Median OS %s years\n", gene, n[1], round(half[1],2)) ,
                                    sprintf("%s low, n=%s\n Median OS %s years\n", gene, n[2], round(half[2],2))),
                    xlab = "Time Since Biopsy (Years)")
  res$table <- res$table + theme(axis.line = element_blank())
  res
}
