#' hchartgenelevel function
#'
#' Draws highchart scatter plot for gene levels
#'
#' @param data data frame generated by patsubset function
#'
#' @import data.table
#' @import highcharter
#'
#' @return interactive scatter plot for gene level across all patients
#'
#' @examples
#' gene <- "SOX10"
#' sox10.pat <- patsubset(pat, rna, gene, 10)
#' hchartgenelevel(sox10.pat)
#'
#' @export
#'
hchartgenelevel <- function(data) {
  setkey(data, level)
  data[, name := factor(name, levels=name)]
  hchart(data, "scatter", x = name, y = level, color = gene2)
}
