#' hchartgenelevel function
#'
#' Draws highchart scatter plot for gene levels
#'
#' @param data data frame generated by rnasubset function
#'
#' @import data.table
#' @import highcharter
#'
#' @return interactive scatter plot for gene level across all patients
#'
#' @examples
#' data(skcm)
#' gene <- "SOX10"
#' sox10.pat <- rnasubset(pat, rna, gene, 10)
#' hchartgenelevel(sox10.pat)
#'
#' @export
#'
hchartgenelevel <- function(data) {
  setkey(data, level)
  data[, `:=` (name2 = factor(name, levels=name))]
  hchart(data, "scatter", x = name2, y = level, color = gene2)
}
