#' plotlycp function
#'
#' Draws plotly plot of copy number matrix
#'
#' @param pat2 data frame generated by patsubset function
#' @param cp data frame of mutation matrix
#' @param gene character(1) gene of interest
#' @param level choose "high" or "low" population
#'
#' @import data.table
#' @import plotly
#'
#' @return interactive oncoprint-like plot for top 15 genes with most copy number aberations
#'
#' @examples
#' gene <- "SOX10"
#' sox10.pat <- patsubset(pat, rna, gene, 10)
#' plotlycp(sox10.pat, cp, gene, "high")
#'
#' @export
#'
plotlycp <- function(pat2, cp, gene, level) {
  setkey(pat2, gene2)
  cp1.high <- data.table(Gene = cp$Gene, N = rowSums(abs(cp[, intersect(pat2[level, name], colnames(cp)), with =F])))
  setkey(cp1.high, N)
  glist <- c(tail(cp1.high[, Gene], 15), gene)
  glist <- glist[!duplicated(glist)]
  setkey(cp, Gene)
  cop1 <- cp[glist,c("Gene", intersect(pat2[level, name], colnames(cp))), with=F]
  cop1 <- cop1[!(is.na(rowSums(cop1[, colnames(cop1)[-1], with=F])))]

  cp.gg1 <- dcast.data.table((melt(cop1, variable.name="name", id.vars="Gene")), name ~ Gene)
  setkeyv(cp.gg1, names(sort(apply(cp.gg1[,colnames(cp.gg1)[-1], with=F], 2, sum), decreasing=T)))
  cp.mut1 <- melt(cp.gg1)

  cp.mut1$name <- factor(cp.mut1$name, levels=rev(cp.gg1$name))
  cp.mut1$variable <- factor(cp.mut1$variable, levels=names(sort(apply(cp.gg1[,colnames(cp.gg1)[-1], with=F], 2, sum), decreasing=F)))
  cg1 <- ggplot(cp.mut1,aes(name,variable,fill=as.factor(value)))+geom_tile(colour=c("white")) +
    labs(x = "Patient", y="Gene") +
    scale_x_discrete(expand=c(0,0))+scale_y_discrete(expand=c(0,0)) +
    scale_fill_manual(values = c("#f1a340", "#f0f0f0", "#998ec3"), labels=c(-1:1), guide = guide_legend(title = "Copy number change") ) +
    theme(title=element_text(size=16), axis.ticks=element_blank(),  axis.text.x=element_blank(), axis.text.y=element_text(size=12), axis.text.x=element_text(size=14), axis.text.y=element_text(size=14), legend.text=element_text(size=12)) +
    ggtitle(paste(gene, level))
  ggplotly(cg1)
}



