#' plotlygenelevel function
#'
#' Draws plotly bar plot for gene levels (log scale)
#'
#' @param data data frame generated by rnasubset function
#'
#' @import data.table
#' @import plotly
#'
#' @return interactive scatter plot for gene level across all patients
#'
#' @examples
#' data(skcm)
#' gene <- "SOX10"
#' sox10.pat <- rnasubset(pat, rna, gene, 10)
#' hchartgenelevel(sox10.pat)
#'
#' @export
#'
plotlygenelevel <- function(data) {
  setkey(data, level)
  data[, `:=` (name2 = factor(name, levels=name),
               `expression (log2)` = log(level + 1, 2)
               )]
  plot_ly(data = data, x = ~name2, y = ~`expression (log2)`, type= "bar", color = ~gene2)
}
