#' plotgenelevel function
#'
#' Plots bar plot for gene levels (log scale)
#'
#' @param mae MultiAssayExperiment generated by rnasubset function, must have assay named Cohort
#'
#' @import ggplot2
#' @importFrom MultiAssayExperiment wideFormat
#'
#' @return interactive scatter plot for gene level across all patients
#'
#' @examples
#' library(curatedTCGAData)
#' library(TCGAutils)
#' lusc <- curatedTCGAData("LUSC", c("Mutation", "RNASeq2GeneNorm", "GISTIC_AllbyGene", "RPPAArray"), FALSE)
#'
#' #split tumor and normal samples
#' lusc_tn <- splitAssays(lusc, c("01", "11"))
#' #remake MultiAssayExperiment with only primary tumor samples
#' lusc_t <- lusc_tn[, , grep("^01", names(lusc_tn))]
#' lusc_egfr <- rnasubset(lusc_t, "EGFR", 10)
#' plotgenelevel(lusc_egfr)
#'
#' @export
#'
plotgenelevel <- function(mae) {
  stopifnot(any(grepl("Cohort", names(mae))))
  geplot <- as.data.frame(wideFormat(mae[c("counts", "level"), ,"Cohort"]))
  geplot$logcounts <- log(as.numeric(as.character(geplot$Cohort_counts)) + 1, 2)
  geplot$Cohort_level <- factor(geplot$Cohort_level, levels = unique(geplot$Cohort_level))
  geplot$Samples <- factor(geplot$primary, levels = geplot$primary[order(geplot$logcounts)])
  ggplot(data = geplot, aes(x = Samples, y = logcounts, color = Cohort_level)) +
    geom_bar() +
    theme_bw()
}
