#' plotlymut function
#'
#' Draws plotly plot of mutations
#'
#' @param pat2 data frame generated by patsubset function
#' @param mut data frame of mutation matrix
#' @param gene character(1) gene of interest
#'
#' @import data.table
#' @import plotly
#'
#' @return interactive oncoprint-like plot for top 15 most mutated genes
#'
#' @examples
#' gene <- "SOX10"
#' sox10 <- patsubset(pat, rna, gene, 10)
#' plotlymut(sox10, mut, gene)
#'
#' @export
#'
plotlymut <- function(pat2, mut, gene) {
  setkey(pat2, gene2)
  m1.high <- data.table(Gene = mut$Gene, N = rowSums(mut[, intersect(pat2["high", bcr_patient_barcode], colnames(mut)), with =F]))
  setkey(m1.high, N)
  glist <- c(tail(m1.high[, Gene], 15), gene)
  glist <- glist[!duplicated(glist)]
  setkey(mut, Gene)
  mut1 <- mut[glist,c("Gene", intersect(pat2["high", bcr_patient_barcode], colnames(mut))), with=F]
  mut1 <- mut1[!(is.na(rowSums(mut1[, colnames(mut1)[-1], with=F])))]
  gg1 <- dcast.data.table((melt(mut1, variable.name="bcr_patient_barcode", id.vars="Gene")), bcr_patient_barcode ~ Gene)
  setkeyv(gg1, names(sort(apply(gg1[,colnames(gg1)[-1], with=F], 2, sum), decreasing=T)))
  mut2 <- melt(gg1)
  mut2$bcr_patient_barcode <- factor(mut2$bcr_patient_barcode, levels=rev(gg1$bcr_patient_barcode))
  mut2$variable <- factor(mut2$variable, levels=names(sort(apply(gg1[,colnames(gg1)[-1], with=F], 2, sum), decreasing=F)))
  gg3 <- ggplot(mut2,aes(bcr_patient_barcode,variable,fill=as.factor(value))) + geom_tile(colour=c("white")) + labs(x = "Patient", y="Gene") +
    theme(title=element_text(size=16), axis.ticks=element_blank(), axis.text.x=element_blank(), axis.text.y=element_text(size=12), axis.title.x=element_text(size=14), axis.title.y=element_text(size=14), legend.text=element_text(size=12)) +
    scale_fill_brewer(type="qual",name="Legend", palette=6, labels=c("Wild-type", "Mutated")) +
    ggtitle(paste(gene, "high"))
    ggplotly(gg3)
}
