#' rnareactplot function
#'
#' Uses ReactomePA to find enriched pathways from the RNAseq differential gene analysis
#'
#' @param react data frame generated by rnareact function
#' @param deg data frame generated by rnadeg function
#' @param graph character(1) type of graph to plot, (dot, map, cnet)
#' @param n numeric(1) number of pathways to plot, default is 10
#'
#' @import gage
#' @import data.table
#' @import ReactomePA
#' @import DOSE
#'
#' @return dotplot or enrichment pathway or cnetmap of Reactome gene sets
#'
#' @examples
#' #using data from the cureatedTCGAdata set
#' library(curatedTCGAData)
#' library(TCGAutils)
#' lusc <- curatedTCGAData("LUSC", c("Mutation", "RNASeq2GeneNorm", "GISTIC_ThresholdedByGene", "RPPAArray"), FALSE)
#'
#' #split tumor and normal samples
#' lusc_tn <- splitAssays(lusc, c("01", "11"))
#' #remake MultiAssayExperiment with only primary tumor samples
#' lusc_t <- lusc_tn[, , grep("^01", names(lusc_tn))]
#' lusc_t.egfr <- rnasubset(lusc_t, "EGFR", 10)
#' egfr_deg <- diffrna(lusc_t.egfr)
#' egfr_react <- rnareact(egfr_deg)
#' plotreact(egfr_react, egfr_deg, "dot", 10)
#' plotreact(egfr_react, egfr_deg, "map", 10)
#' plotreact(egfr_react, egfr_deg, "cnet", 10)
#' @export
#'
plotreact <- function(react, deg, graph, n = 10) {
  switch(graph,
         "dot" = dotplot(react, showCategory=n),
         "map" = emapplot(react, n=n, vertex.label.cex = 1),
         "cnet" = cnetplot(react, showCategory = n, categorySize="pvalue", foldChange=deg$logFC))
}
