#' plotlygenelevel function
#'
#' Draws plotly bar plot for gene levels
#'
#' @param data data frame generated by patsubset function
#'
#' @import data.table
#' @import highcharter
#'
#' @return interactive scatter plot for gene level across all patients
#'
#' @examples
#' gene <- "SOX10"
#' sox10 <- patsubset(pat, rna, gene, 10)
#' hchartgenelevel(sox10)
#'
#' @export
#'
plotlygenelevel <- function(data) {
  setkey(data, level)
  data[, name := factor(name, levels=name)]
  plot_ly(data = data, x = ~name, y = ~level, type= "bar", color = ~gene2)
}
