#' plotlymut function
#'
#' Draws plotly plot of mutations
#'
#' @param pat2 data frame generated by patsubset function
#' @param mut data frame of mutation matrix
#' @param gene character(1) gene of interest
#' @param level choose "high" or "low" population
#'
#' @import data.table
#' @import plotly
#'
#' @return interactive oncoprint-like plot for top 15 most mutated genes
#'
#' @examples
#' gene <- "SOX10"
#' sox10 <- patsubset(pat, rna, gene, 10)
#' plotlymut(sox10, mut, gene, "high")
#'
#' @export
#'
plotlymut <- function(pat2, mut, gene, level) {
  setkey(pat2, gene2)
  #gets patients with rnaseq, clinical and mutation data
  overlap <- intersect(pat2[level, bcr_patient_barcode], colnames(mut))

  #calculates most mutated genes in the overlap patients
  m1.high <- data.table(Gene = mut$Gene, N = rowSums(mut[, overlap, with =FALSE]))
  setkey(m1.high, N)

  #takes top 15 mutated genes and gene of interest
  glist <- c(tail(m1.high[, Gene], 15), gene)
  glist <- glist[!duplicated(glist)]
  setkey(mut, Gene)
  mut1 <- mut[glist,c("Gene", overlap), with=FALSE]
  mut1 <- mut1[!(is.na(rowSums(mut1[, colnames(mut1)[-1], with=FALSE])))]

  #gets order of patients
  mut1.melt <- melt(mut1, variable.name="bcr_patient_barcode", id.vars="Gene")
  gg1 <- dcast.data.table(mut1.melt, bcr_patient_barcode ~ Gene)
  gene.order <- names(sort(apply(gg1[,colnames(gg1)[-1], with=F], 2, sum), decreasing=T))
  setkeyv(gg1, gene.order)

  mut1.melt$bcr_patient_barcode <- factor(mut1.melt$bcr_patient_barcode, levels=rev(gg1$bcr_patient_barcode))
  mut1.melt$Gene <- factor(mut1.melt$Gene, levels=rev(gene.order))
  gg3 <- ggplot(mut1.melt,aes(bcr_patient_barcode,Gene,fill=as.factor(value))) + geom_tile(colour=c("white")) + labs(x = "Patient", y="Gene") +
    theme(title=element_text(size=16), axis.ticks=element_blank(), axis.text.x=element_blank(), axis.text.y=element_text(size=12), axis.title.x=element_text(size=14), axis.title.y=element_text(size=14), legend.text=element_text(size=12)) +
    scale_fill_brewer(type="qual",name="Legend", palette=6, labels=c("Wild-type", "Mutated")) +
    ggtitle(paste(gene, level))
  ggplotly(gg3)
}
