#' rnagsva function
#'
#' Uses GSVA to find gene set enrichment across samples
#'
#' @param pat2 data frame generated by rnasubset function
#' @param rna data frame of RNAseq values
#'
#' @import data.table
#' @import GSVA
#' @import limma
#' @import GSVAdata
#' @import parallel
#' @import GSVAdata
#'
#' @return data frame of gsva values for all samples
#'
#' @examples
#' data(skcm)
#' gene <- "SOX10"
#' sox10.pat <- rnasubset(pat, rna, gene, 10)
#' sox10.deg <- rnadeg(sox10.pat, rna)
#' sox10.gsva <- rnagsva(sox10.pat, rna)
#'
#' @export
#'
rnagsva <- function(pat2, rna) {
  data(c2BroadSets)
  setkey(pat2, gene2)
  d1.gsva <- as.matrix(rna[,pat2[!("middle"), name], with=F])
  rownames(d1.gsva) <- lookup$entrez[match(rna$Gene, lookup$gene)]
  gsva(d1.gsva, c2BroadSets, min.sz=5, max.sz=500, mx.diff=TRUE, verbose=TRUE, rnaseq=TRUE)
}
