#' rnagsvasig function
#'
#' Uses GSVA to find gene set enrichment across samples
#'
#' @param pat2 data frame generated by patsubset function
#' @param rnagsva data frame generated by rnagsva
#'
#' @import limma
#' @import data.table
#'
#' @return data frame of logFC values for gene sets
#'
#' @examples
#' gene <- "SOX10"
#' sox10.pat <- patsubset(pat, rna, gene, 10)
#' sox10.deg <- rnadeg(sox10.pat, rna)
#' sox10.gsva <- rnagsva(sox10.pat, sox10.deg)
#' sox10.gsva.sig <- rnagsvasig(sox10.pat, sox10.gsva)
#'
#' @export
#'
rnagsvasig <- function(pat2, rnagsva) {
  setkey(pat2, gene2)
  design <- model.matrix(~factor(pat2[!("middle"),gene2], levels=c("low", "high")))
  fit <- lmFit(rnagsva$es.obs, design)
  fit <- eBayes(fit)
  topTable(fit, coef=2, number=Inf, p.value=0.05, adjust="BH")
}

