#' rnamethdeg function
#'
#' Uses limma to find differentially methylated islands between the high and low groups
#'
#' @param pat2 data frame generated by rnasubset function
#' @param meth data frame of CpG Island methylation values
#'
#' @import data.table
#' @import edgeR
#' @import limma
#'
#' @return data frame of significant differentially methylated islands between the two groups defined in rnasubset or mutsubset
#'
#' @examples
#' data(skcm)
#' gene <- "SOX10"
#' sox10.rna <- rnasubset(pat, rna, gene, 10)
#' sox10.methdeg <- rnamethdeg(sox10.rna, meth)
#'
#' @export
#'
rnamethdeg <- function(pat2, meth) {
  setkey(pat2, gene2)
  meth.pat <- pat2[intersect(colnames(meth), pat2[pat2$gene2 != "middle", name])]

  meth.gene <- as.matrix(meth[,meth.pat$name, with=F])
  rownames(meth.gene) <- meth$Island_Name

  design <- model.matrix(~factor(meth.pat[,gene2], levels=c(levels(meth.pat$gene2)[2], levels(meth.pat$gene2)[1])))
  fit <- lmFit(asin(meth.gene), design)

  fit2 <- eBayes(fit, trend = TRUE)
  fit3 <- topTable(fit2, coef=2, n=Inf, adjust.method="BH", p.value=0.05, lfc = 0.1, sort="p")
  fit3

}
