#' rnareact function
#'
#' Uses ReactomePA to find enriched pathways from the RNAseq differential gene analysis
#'
#' @param rnadeg data frame generated by topTable of limma output
#' @param lookup data frame of entrez ID and gene name pairs
#' @param n numeric(1) number of pathways to plot
#' @param graph character(1) type of graph to plot, (dot, map, cnet)
#'
#' @import gage
#' @import data.table
#' @import ReactomePA
#' @import DOSE
#'
#' @return dotplot or enrichment pathway or cnetmap of Reactome gene sets
#'
#' @examples
#' gene <- "SOX10"
#' sox10.pat <- patsubset(pat, rna, gene, 10)
#' sox10.deg <- rnadeg(sox10.pat, rna)
#' rnareact(sox10.deg, lookup, 10, "dot")
#' rnareact(sox10.deg, lookup, 10, "map")
#' rnareact(sox10.deg, lookup, 10, "cnet")
#'
#' @export
#'
rnareact <- function(deg, lookup, n, graph) {
  limma.fc <- deg$logFC
  names(limma.fc) <- lookup$entrez[match(deg$genes, lookup$gene)]
  limma.names <- lookup$entrez[match(deg$genes, lookup$gene)]
  x <- enrichPathway(gene = limma.names, pvalueCutoff=0.05, readable=T)
  switch(graph,
         "dot" = dotplot(x, showCategory=n),
         "map" = enrichMap(x, n=n, layout=igraph::layout.kamada.kawai, vertex.label.cex = 1),
         "cnet" = cnetplot(x, showCategory = n, categorySize="pvalue", foldChange=limma.fc))
}

