#' rnareact function
#'
#' Uses ReactomePA to find enriched pathways from the RNAseq differential gene analysis
#'
#' @param rnadeg data frame generated by topTable of limma output
#' @param lookup data frame of entrez ID and gene name pairs
#'
#' @import gage
#' @import data.table
#' @import ReactomePA
#' @import DOSE
#'
#' @return data frame of enrichment for Reactome gene sets
#'
#' @examples
#' gene <- "SOX10"
#' sox10.pat <- patsubset(pat, rna, gene, 10)
#' sox10.deg <- rnadeg(sox10.pat, rna)
#' sox10.react <- rnareact(sox10.deg, lookup)
#'
#' @export
#'
rnareact <- function(deg, lookup) {
  limma.fc <- deg$logFC
  names(limma.fc) <- lookup$entrez[match(deg$genes, lookup$gene)]
  limma.names <- lookup$entrez[match(deg$genes, lookup$gene)]
  x <- enrichPathway(gene = limma.names, pvalueCutoff=0.05, readable=T)
}

