#' rnareactdot function
#'
#' Uses ReactomePA to find enriched pathways from the RNAseq differential gene analysis
#'
#' @param rnadeg data frame generated by topTable of limma output
#' @param lookup data frame of entrez ID and gene name pairs
#' @param n numeric(1) number of pathways to plot
#' @param graph character(1) type of graph to plot, (dot, map, cnet)
#'
#' @import gage
#' @import data.table
#'
#' @return dot plot of Reactome enrichment
#'
#' @examples
#' gene <- "SOX10"
#' sox10.pat <- patsubset(pat, rna, gene, 10)
#' sox10.deg <- rnadeg(sox10.pat, rna)
#' rnareactdot(sox10.deg, lookup, 20)
#'
#' @export
rnareact <- function(rnadeg, lookup, n, graph) {
  limma.fc <- rnadeg$logFC
  names(limma.fc) <- lookup$entrez[match(rnadeg$genes, lookup$gene)]
  x <- enrichPathway(gene=limma.fc,pvalueCutoff=0.05, readable=T)
  switch(graph,
         "dot" = dotplot(x, showCategory=n),
         "map" = enrichMap(x, n=n, layout=igraph::layout.kamada.kawai, vertex.label.cex = 1),
         "cnet" = cnetplot(x, showCategory = n, categorySize="pvalue", foldChange=limma.fc))
}

