#' rnasubset function
#'
#' subsets rnaseq table for patient chosen in analysis
#'
#' @param pat2 data frame generated by patsubset function
#' @param rna data frame of RNAseq values
#'
#' @import data.table
#'
#' @return data frame of RNAseq values for only patients in the high and low gene expression groups
#'
#' @examples
#' gene <- "SOX10"
#' sox10.pat <- patsubset(pat, rna, gene, 10)
#' sox10.rna <- rnsubset(sox10.pat, rna)
#'
#' @export
#'
rnasubset <- function(pat2, rna) {
  setkey(pat2, gene2)
  rna[, c("Gene", as.character(pat2[!("middle"), name])), with=F]
}
