#' rppadeg function
#'
#' Uses limma to find differentially expressed proteins between the high and low groups
#'
#' @param pat2 data frame generated by rnasubset function
#' @param rppa data frame of RPPA values
#'
#' @import data.table
#' @import edgeR
#' @import limma
#'
#' @return data frame of significant differentially expressed proteins between the two groups defined in rnasubset or mutsubset
#'
#' @examples
#' data(skcm)
#' gene <- "SOX10"
#' sox10.pat <- rnasubset(pat, rna, gene, 10)
#' sox10.deg <- rppadeg(sox10.pat, rppa)
#'
#' @export
#'
rppadeg <- function(pat2, rppa) {
  setkey(pat2, name)
  rppa.pat <- pat2[intersect(colnames(rppa), pat2[pat2$gene2 != "middle", name])]

  rppa.gene <- as.matrix(rppa[,rppa.pat$name, with=F])
  rownames(rppa.gene) <- rppa$CE.REF

  design <- model.matrix(~factor(rppa.pat[,gene2], levels=c(levels(rppa.pat$gene2)[2], levels(rppa.pat$gene2)[1])))
  fit <- lmFit(rppa.gene, design)
  fit2 <- eBayes(fit)
  fit3 <- topTable(fit2, coef=2, n=Inf, adjust.method="BH", p.value=0.05, lfc=1,sort="p")
  fit3
}
